// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqnwlvrnnqweljibarfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xbndsdnJubnF3ZWxqaWJhcmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNDcyMTQsImV4cCI6MjA1NTcyMzIxNH0.SIk0DoO5h4CNsXP_lCTTT2964MbcLh98WnBpzpjazj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});