// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xenwodrcjavrmfjbtwwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlbndvZHJjamF2cm1mamJ0d3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMzA3NDgsImV4cCI6MjA3NjgwNjc0OH0.AL3zOyujKIs3Zm-mXfhOX4V_5oLLqmuosBpTbfF8Bbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
